version: '3'
services:
  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../:/var/www/app
    ports:
      - '80:9000'
    depends_on:
      - app
    links:
      - app

  app: 
    build:
      context: ./
      dockerfile: ./DockerFile
    volumes:
      - ../:/var/www/app
    environment:
      DB_HOST: db
      DB_CONNECTION: mysql
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      DB_ENGINE: InnoDB
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    volumes:
      - $HOME/.composer:/.composer
      - ../:/var/www/app
    links: 
      - db
      - redis

  db:
    image: mysql 
    command: --default-authentication-plugin=mysql_native_password 
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  redis:
    image: redis:alpine
